import { Denuncia } from "./denuncia";
import { DenunciaPorMenorEdad } from "./denuncia-nna";
import { DetalleImputado } from "./detalle-imputado";
import { Detencion } from "./detencion";
import { Direccion } from "./direccion";
import { EstadoInvolucrado } from "./estado-involucrado";
import { InvolucradoDenunciado } from "./involucrado-denunciado";
import { MedioTransporteInvolucrado } from "./medio-transporte-involucrado";
import { NarracionDenuncia } from "./narracion-denuncia";
import { PerfilImputado } from "./perfil-imputado";
import { RolImputado } from "./rol-imputado";
import { TpContactoDenuncia } from "./tp-contacto-denuncia";
import { TpInvolucrado } from "./tp-involucrado";
// import { TpRelacion } from "./tp-relacion";
import { TpSituacionConvivencia } from "./tp-situacion-convivencia";

export interface Involucrado {
    idInvolucrado:              number;
    idPersonaParte:             number;
    direccion:                  Direccion;
    tpContactoDenuncia:         TpContactoDenuncia;
    tpSituacionConvivencia:     TpSituacionConvivencia;
    tpInvolucrado:              TpInvolucrado;
    estadoInvolucrado:          EstadoInvolucrado[];
    rolImputado:                RolImputado[];
    denunciaPorMenorEdad:       DenunciaPorMenorEdad[];
    perfilImputado:             PerfilImputado[];
    medioTransporteInvolucrado: MedioTransporteInvolucrado[];
    detalleImputado:            DetalleImputado[];
    detencion:                  Detencion[];
    involucrado:                InvolucradoDenunciado[];
    involucradoDenunciado:      InvolucradoDenunciado[];
    narracionDenuncia:          NarracionDenuncia[];
    fcIngreso:                  Date;
    glDetalleLesiones:          string;
    glOtrosTestigos:            string;
    glPruebaHechos:             string;
    fcExpiracion:               Date;
    nrRutUsuario:               number;
}